services:
  backend:
    build: ./backend
    container_name: temp-file-share
    restart: unless-stopped
    expose:
      - "54000"
    networks:
      - pangolin
    volumes:
      - "/opt/temp-file-share/uploads:/app/uploads"
      - "/opt/temp-file-share/data:/app/data"
    environment:
      TZ: Asia/Manila

networks:
  pangolin:
    external: true
